### ISSUE TITLE
不能使用自定义mode

### ISSUE THREAD

**Issue by varHarrie** [surmon-china/vue-codemirror#10]
使用了[这里](http://jsfiddle.net/TcqAf/99/)的代码，复制进去，运行报错：

> Error: CodeMirror language mode: mymode configuration error (CodeMirror语言模式配置错误，或者不支持此语言)

还是说根本不支持自定义mode...

**Comment by surmon-china** [comment]
已修复此问题，请升级至v2.1.6
https://github.com/surmon-china/vue-codemirror/releases/tag/v2.1.6
