### ISSUE TITLE
codemirror版本问题

### ISSUE THREAD

**Issue by daxiewang** [surmon-china/vue-codemirror#102]
安装的时候自动装了codemirror最新版，语言无法高亮了，但以前装的老的版本是可以正常使用的，因为当时自动安装的codemirror版本是5.41.0，是不是api改动了

**Comment by followbin** [comment]
同遇到不能高亮，但是有基本颜色样式

**Comment by luozejian** [comment]
问题解决了吗?一样的问题

**Comment by mocobk** [comment]
同问

**Comment by brianzhang** [comment]
有遇到代码第一次加载，换行代码不能选择到尾部的代码段

**Comment by aoyeQ** [comment]
> 有遇到代码第一次加载的代码，不能选择切换到的代码段

同遇到，请问解决了吗
