### ISSUE TITLE
Mode "text/plain" blows up with an error.

### ISSUE THREAD

**Issue by euvl** [surmon-china/vue-codemirror#12]
When setting `mode: "text/plain"` in codemirror options, an error occurs:
`vue.common.js?e881:435` Error: Cannot find module './null/null.js'.

Might be due to the fact that `metas.js` file contains this record (with mode being "null" string):
```
{
  name: "Plain Text", 
  mime: "text/plain", 
  mode: "null", 
  ext: ["txt", "text", "conf", "def", "list", "log"]
}
```

**Comment by surmon-china** [comment]
Version 2.1.7 has resolved this issue.
https://github.com/surmon-china/vue-codemirror/releases/tag/v2.1.7
