### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by Yakoot** [surmon-china/vue-codemirror#124]
are you planning to support vue 3?

**Comment by Hzw576816** [comment]
+1

**Comment by githubzaibao** [comment]
+1

**Comment by githubzaibao** [comment]
+1

**Comment by githubzaibao** [comment]
+1

**Comment by Mvsvh** [comment]
+1

**Comment by Longgererer** [comment]
+1,+1 AAAAAAAAAnd +1!!!

**Comment by sweco-dkjesh** [comment]
It seems vue-codemirror is very close to Vue3 compliant.
I found 3 things needed to be done to make it work:

1. remove `content`, `codemirror` and `cmintance` from data
2. change `beforeDestroy `=> `beforeUnmount`
3. Handle typescript errors
E.g. by ignoring (not the best option / but the simple one)
```
//@ts-ignore
import VueCodeMirror from "@/components/codemirror.vue";
```

**Comment by wangweiqiangs** [comment]
什么时候能支持一下呢

**Comment by RennCheung** [comment]
vue3版本：https://github.com/RennCheung/codemirror-editor-vue3

**Comment by surmon-china** [comment]
[v5.0.0](https://github.com/surmon-china/vue-codemirror/tree/v5.0.0)
