### ISSUE TITLE
Consider adding support for CodeMirror Lint mode

### ISSUE THREAD

**Issue by kkinder** [surmon-china/vue-codemirror#13]
If you include `{lint: true}` in your config, perhaps vue-codemirror should import the requisite lint addon and configure it.

**Comment by danmindru** [comment]
There's https://github.com/sireniaeu/vue2-codemirror-lite-js if you are only interested in JS + linting in a lightweight bundle. Otherwise this repo has a ton more features.

**Comment by dudesweet100** [comment]
Will this lib support linting?

**Comment by surmon-china** [comment]
https://github.com/surmon-china/vue-codemirror/blob/master/examples/02-text-javascript.vue
