### ISSUE TITLE
[HowTo] Accessing the codemirror object

### ISSUE THREAD

**Issue by kaushikrishi** [surmon-china/vue-codemirror#136]
How can I access the codemirror instance for using it in other packages like codemirror record?
https://github.com/Jisuanke/CodeMirror-Record

**Comment by eliottvincent** [comment]
Easy! Just add a `@ready` event handler to the component.

In your template:
```
codemirror(
  @ready="onCodeMirrorReady"
  ...
)
```

In your methods:
```
onCodeMirrorReady(codeMirror) {
  // Save CodeMirror instance
  this.codeMirror = codeMirror;
},
```

**Comment by kaushikrishi** [comment]
Thanks @eliottvincent

**Comment by kaushikrishi** [comment]
Thanks, it is working, have tested the code in nuxt js.

**Comment by brizer** [comment]
> Easy! Just add a `@ready` event handler to the component.
> 
> In your template:
> 
> ```
> codemirror(
>   @ready="onCodeMirrorReady"
>   ...
> )
> ```
> 
> In your methods:
> 
> ```
> onCodeMirrorReady(codeMirror) {
>   // Save CodeMirror instance
>   this.codeMirror = codeMirror;
> },
> ```

It is should be added in readme doc.
