### ISSUE TITLE
Suggestions for supporting the Vue3 release

### ISSUE THREAD

**Issue by RennCheung** [surmon-china/vue-codemirror#137]
### Suggestions for supporting the Vue3 release
Because I need to use it in vue3, I changed to vue3 based on your plugin, so if I publish the npm package, it may infringe your interests, and I am too lazy to rewrite a document, but if you want, I You can become a contributor to this repository and support the vue version to this plugin

**Comment by Longgererer** [comment]
Support!

> ### Suggestions for supporting the Vue3 release
> Because I need to use it in vue3, I changed to vue3 based on your plugin, so if I publish the npm package, it may infringe your interests, and I am too lazy to rewrite a document, but if you want, I You can become a contributor to this repository and support the vue version to this plugin

**Comment by RennCheung** [comment]
https://github.com/RennCheung/codemirror-editor-vue3
