### ISSUE TITLE
Useful examples

### ISSUE THREAD

**Issue by estevanmaito** [surmon-china/vue-codemirror#14]
Could you provide a complete working example that can be run locally?

Take this as an example: https://github.com/surmon-china/vue-codemirror/blob/master/examples/-1-default-vue.vue

Where does the component "codemirror" comes from? What is the current bundle system? How is it configured?

Copying  some of the examples and trying to add the component to the project following the instructions lead me to errors like this:

```
[Vue warn]: Failed to mount component: template or render function not defined. 
(found in component <codemirror>)
```

**Comment by surmon-china** [comment]
``` javascript
// import
import Vue from 'vue'
import VueCodeMirror from 'vue-codemirror'


// or require
var Vue = require('vue')
var VueCodeMirror = require('vue-codemirror')


// global use
Vue.use(VueCodeMirror)
```
