### ISSUE TITLE
@codemirror/state are loaded, breaking instanceof checks.

### ISSUE THREAD

**Issue by servens** [surmon-china/vue-codemirror#148]
### Describe the bug

vue-router.esm-bundler.js:3302 Error: Unrecognized extension value in extension set ([object Object]). This sometimes happens because multiple instances of @codemirror/state are loaded, breaking instanceof checks.
    at inner (index.js:2004:23)
    at inner (index.js:1979:17)
    at inner (index.js:2005:13)
    at inner (index.js:1979:17)
    at inner (index.js:2005:13)
    at inner (index.js:1979:17)
    at inner (index.js:1986:13)
    at inner (index.js:1979:17)
    at flatten (index.js:2008:5)
    at Configuration.resolve (index.js:1916:25)
triggerError @ vue-router.esm-bundler.js:3302
(anonymous) @ vue-router.esm-bundler.js:3338
Promise.catch (async)
handleScroll @ vue-router.esm-bundler.js:3338
finalizeNavigation @ vue-router.esm-bundler.js:3195
(anonymous) @ vue-router.esm-bundler.js:3067
Promise.then (async)
pushWithRedirect @ vue-router.esm-bundler.js:3038
push @ vue-router.esm-bundler.js:2966
install @ vue-router.esm-bundler.js:3380
use @ runtime-core.esm-bundler.js:3808
(anonymous) @ main.ts:20
index.js:2004 Uncaught (in promise) Error: Unrecognized extension value in extension set ([object Object]). This sometimes happens because multiple instances of @codemirror/state are loaded, breaking instanceof checks.
    at inner (index.js:2004:23)
    at inner (index.js:1979:17)
    at inner (index.js:2005:13)
    at inner (index.js:1979:17)
    at inner (index.js:2005:13)
    at inner (index.js:1979:17)
    at inner (index.js:1986:13)
    at inner (index.js:1979:17)
    at flatten (index.js:2008:5)
    at Configuration.resolve (index.js:1916:25)

### Reproduction

not

### System Info

```shell
npx: installed 1 in 2.744s

  System:
    OS: macOS 12.0.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 153.63 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.1 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 6.14.16 - /usr/local/bin/npm
  Browsers:
    Chrome: 102.0.5005.115
    Safari: 15.1
  npmPackages:
    @arco-design/web-vue: ^2.29.0 => 2.29.0 
    @codemirror/lang-html: ^6.0.0 => 6.0.0 
    @codemirror/lang-javascript: ^6.0.0 => 6.0.0 
    @codemirror/lang-json: ^6.0.0 => 6.0.0 
    @codemirror/theme-one-dark: ^6.0.0 => 6.0.0 
    @commitlint/cli: ^11.0.0 => 11.0.0 
    @commitlint/config-conventional: ^12.0.1 => 12.1.4 
    @types/lodash: ^4.14.177 => 4.14.178 
    @types/mockjs: ^1.0.4 => 1.0.5 
    @types/nprogress: ^0.2.0 => 0.2.0 
    @typescript-eslint/eslint-plugin: ^5.10.0 => 5.10.0 
    @typescript-eslint/parser: ^5.10.0 => 5.10.0 
    @vitejs/plugin-vue: ^1.9.4 => 1.10.2 
    @vitejs/plugin-vue-jsx: ^1.2.0 => 1.3.3 
    @vue/babel-plugin-jsx: ^1.1.1 => 1.1.1 
    @vueuse/core: ^7.3.0 => 7.5.3 
    arco-design-pro-vue: ^2.5.3 => 2.5.3 
    axios: ^0.24.0 => 0.24.0 
    cross-env: ^7.0.3 => 7.0.3 
    dayjs: ^1.10.7 => 1.10.7 
    echarts: ^5.2.2 => 5.2.2 
    eslint: ^8.7.0 => 8.7.0 
    eslint-config-airbnb-base: ^14.2.1 => 14.2.1 
    eslint-config-prettier: ^8.3.0 => 8.3.0 
    eslint-import-resolver-typescript: ^2.4.0 => 2.5.0 
    eslint-plugin-import: ^2.22.1 => 2.25.4 
    eslint-plugin-prettier: ^3.3.1 => 3.4.1 
    eslint-plugin-vue: ^8.3.0 => 8.3.0 
    husky: ^7.0.4 => 7.0.4 
    less: ^4.1.2 => 4.1.2 
    lint-staged: ^11.2.6 => 11.2.6 
    lodash: ^4.17.21 => 4.17.21 
    mitt: ^3.0.0 => 3.0.0 
    mockjs: ^1.1.0 => 1.1.0 
    nprogress: ^0.2.0 => 0.2.0 
    pinia: ^2.0.9 => 2.0.9 
    prettier: ^2.2.1 => 2.5.1 
    query-string: ^7.0.1 => 7.1.0 
    rollup-plugin-visualizer: ^5.6.0 => 5.6.0 
    stylelint: ^13.8.0 => 13.13.1 
    stylelint-config-prettier: ^8.0.2 => 8.0.2 
    stylelint-config-rational-order: ^0.1.2 => 0.1.2 
    stylelint-config-standard: ^20.0.0 => 20.0.0 
    stylelint-order: ^4.1.0 => 4.1.0 
    typescript: ^4.5.5 => 4.5.5 
    unplugin-vue-components: ^0.19.3 => 0.19.3 
    vite: ^2.6.4 => 2.7.10 
    vite-plugin-compression: ^0.5.1 => 0.5.1 
    vite-plugin-eslint: ^1.3.0 => 1.3.0 
    vite-plugin-imagemin: ^0.6.1 => 0.6.1 
    vite-plugin-style-import: 1.4.1 => 1.4.1 
    vite-svg-loader: ^3.1.0 => 3.1.1 
    vue: ^3.2.31 => 3.2.31 
    vue-codemirror: ^5.0.1 => 5.0.1 
    vue-echarts: ^6.0.0 => 6.0.0 
    vue-i18n: ^9.2.0-beta.17 => 9.2.0-beta.26 
    vue-router: ^4.0.14 => 4.0.14 
    vue-tsc: ^0.34.15 => 0.34.15
```

### Used Package Manager

npm

### Validations

- [X] Read the the documentation in detail.
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a GitHub Discussion or join our [Discord Chat Server](https://discord.surmon.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by disarticulate** [comment]
check this: https://github.com/codemirror/dev/issues/861

One of your @codemirror or other extensions may be using an old version of codemirror. check the package.json of dependencies.

**Comment by surmon-china** [comment]
@servens @disarticulate 

Yes, this is due to the fact that codemirror recently released an [official v6.0 version](https://github.com/codemirror/basic-setup/blob/main/CHANGELOG.md#600-2022-06-08), resulting in a mismatch between the internal dependency version of vue-codemirror and the plugin version, which I believe is fixed in [vue-codemiror@5.1.0](https://github.com/surmon-china/vue-codemirror/blob/main/CHANGELOG.md#v510-2022-06-12), just remove `node_modules` and `yarn.lock` and reinstall and you're good to go.

**Comment by servens** [comment]
@surmon-china  Thank you very much. The problem has been solved after the upgrade.

**Comment by KaKi87** [comment]
Hello,
I'm experiencing this error with `vue-codemirror` v6.1.1 & `codemirror` v6.0.1
Thanks

**Comment by enzi077** [comment]
> Hello, I'm experiencing this error with `vue-codemirror` v6.1.1 & `codemirror` v6.0.1 Thanks

@KaKi87 any update on this? Cus i too am facing the same issue

**Comment by KaKi87** [comment]
That's a question for @surmon-china.
