### ISSUE TITLE
Cannot import EditorView from vue-codemirror

### ISSUE THREAD

**Issue by felixhao28** [surmon-china/vue-codemirror#149]
### Describe the bug

After upgrading to vue-codemirror 5.1.0,  vue-codemirror no longer exports things from `@codemirror/view` `@codemirror/state` `@codemirror/basic-setup`. I see that's an intended (yet breaking) change in https://github.com/surmon-china/vue-codemirror/commit/f3d4ee77380931aa5c94c1edcbeca0c6e22533db. Then how do we access the dependent codemirror package?

Another note: any breaking change should only be included in **major** version number update. You used minor number and that is not for breaking changes.

### Reproduction

```typescript
import { EditorView } from "vue-codemirror"
```

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 17.73 GB / 31.83 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.10.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 102.0.5005.115
    Edge: Spartan (44.22000.120.0), Chromium (102.0.1245.39)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @types/express: ^4.17.13 => 4.17.13
    @types/node: ^17.0.35 => 17.0.35
    @typescript-eslint/eslint-plugin: ^5.26.0 => 5.26.0
    @typescript-eslint/parser: ^5.26.0 => 5.26.0
    axios: ^0.27.2 => 0.27.2
    dequeue: ^1.0.5 => 1.0.5
    eslint: ^8.16.0 => 8.16.0
    eslint-plugin-import: ^2.26.0 => 2.26.0
    eslint-plugin-node: ^11.1.0 => 11.1.0
    eslint-plugin-standard: ^5.0.0 => 5.0.0
    express: ^4.18.1 => 4.18.1
    form-data: ^4.0.0 => 4.0.0
    humanize-duration: ^3.27.2 => 3.27.2
    lru-cache: ^7.10.1 => 7.10.1
    prettier: 2.6.2 => 2.6.2
    prettier-plugin-java: ^1.6.2 => 1.6.2
    standardx: ^7.0.0 => 7.0.0
    ts-loader: ^9.3.0 => 9.3.0
    typescript: ^4.7.2 => 4.7.2
    webpack: ^5.72.1 => 5.72.1
    webpack-cli: ^4.9.2 => 4.9.2
```

### Used Package Manager

npm

### Validations

- [X] Read the the documentation in detail.
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a GitHub Discussion or join our [Discord Chat Server](https://discord.surmon.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by felixhao28** [comment]
To fix this, you need to:

1. Pull down the v5.1.0 from npm/yarn.
2. Add the exports back.
3. Publish it as v5.1.1, so those already with v5.1.0 can update to v5.1.1 to fix the missing import issue.
4. If you really intend to remove the exports, remove the exports and publish it as v6.0.0.

**Comment by surmon-china** [comment]
@felixhao28 

> "any breaking change should only be included in major version number updates"

Yes, this is correct.

Since CodeMirror@6 released a breaking update that only updates the version number, vue-codemirror was upgraded and I realized that exporting CodeMirror raw packages could lead to naming conflicts and unbounded module fields, so exports were removed.

If you need to import the relevant CodeMirror interface, you need to explicitly declare a dependency on the CodeMirror package in your project, but the version of the dependency needs to be consistent with vue-codemirror, and it is recommended that you use `6.x` as the dependency version number.

I'll be releasing a major version soon, and adding the corresponding documentation.
