### ISSUE TITLE
动态改变editorOption

### ISSUE THREAD

**Issue by GuessEver** [surmon-china/vue-codemirror#15]
比如我想动态改变语言mode

**Comment by GuessEver** [comment]
直接该editorOption变量的话，切换的时候代码会消失，而且语法高亮似乎也并没有改变

**Comment by virusdefender** [comment]
你可能需要自己去watch一下option，然后调用`$refs.myEditor.editor.setOption()`方法

**Comment by surmon-china** [comment]
@virusdefender 好办法！

**Comment by yandwuhan** [comment]
@virusdefender @surmon-china 我用了$refs.myEditor.editor.setOption()方法之后，打印选项来看mode的值被改变了，但是语法高亮和提示功能全部没了，就像mode为空一样，所有语言都不匹配了

**Comment by virusdefender** [comment]
@yandwuhan 我记得遇见过，我想下怎么解决的。貌似是我手误写错了一个地方。

**Comment by virusdefender** [comment]
@yandwuhan 麻烦贴下代码吧。

**Comment by yandwuhan** [comment]
我后来的解决办法是把你的那个又封装了一层，在外层传入codemirror配置参数，和挂载的id，然后每个文本框新建一个vue实例






在 2017-03-02 15:02:06，"李扬" <notifications@github.com> 写道：


@yandwuhan 麻烦贴下代码吧。

**Comment by virusdefender** [comment]
@yandwuhan 之前忘说了。。你可以看下我的用法

https://github.com/QingdaoU/OnlineJudgeFE/blob/master/src/components/CodeMirror.vue
https://github.com/QingdaoU/OnlineJudgeFE/blob/master/src/views/problem/Problem.vue

**Comment by surmon-china** [comment]
v3.0.0 will fix it.
