### ISSUE TITLE
Key binding of "Mod-Enter" doesn't work for some reason

### ISSUE THREAD

**Issue by nhumrich** [surmon-china/vue-codemirror#150]
### Describe the bug

If I am using this component, and try to set a codemirror extension for Mod-Enter, it doesn't work. If I use Shift-Enter or Alt-Enter, it does work, but for some reason, Mod-Enter does not work.

I have tried doing this same thing with codemirror directly, and bypassing this library, but the issue only happens when I am using this library. 

### Reproduction

You can see an example here: https://github.com/nhumrich/code-mirror-issue-repo/blob/main/src/components/CodeEditor.vue

I have added a key binding for both Shift-Enter and Mod-Enter. The Shift-Enter one works while the Mod-Enter one doesn't

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 7.78 GB / 23.84 GB
  Binaries:
    Node: 17.9.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (103.0.1264.37)
  npmPackages:
    @babel/core: ^7.12.16 => 7.18.5
    @babel/eslint-parser: ^7.12.16 => 7.18.2
    @codemirror/lang-sql: ^6.0.0 => 6.0.0
    @codemirror/view: ^6.0.2 => 6.0.2
    @vue/cli-plugin-babel: ~5.0.0 => 5.0.6
    @vue/cli-plugin-eslint: ~5.0.0 => 5.0.6
    @vue/cli-service: ~5.0.0 => 5.0.6
    codemirror: ^6.0.0 => 6.0.0
    core-js: ^3.8.3 => 3.23.2
    eslint: ^7.32.0 => 7.32.0
    eslint-plugin-vue: ^8.0.3 => 8.7.1
    vue: ^3.2.13 => 3.2.37
    vue-codemirror: ^6.0.0 => 6.0.0
```

### Used Package Manager

npm

### Validations

- [X] Read the the documentation in detail.
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a GitHub Discussion or join our [Discord Chat Server](https://discord.surmon.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by surmon-china** [comment]
Hi! @nhumrich 

I think this problem is caused by the fact that the [codemirror/basic-setup](https://github.com/codemirror/basic-setup) package already contains the "Mod-Enter" keybindings, you can find the relevant code in the following order.

1. https://github.com/surmon-china/vue-codemirror/blob/main/src/component.ts#L48
2. https://github.com/codemirror/basic-setup/blob/main/src/codemirror.ts#L67
3. https://github.com/codemirror/commands/blob/main/src/commands.ts#L871
4. https://github.com/codemirror/commands/blob/main/src/commands.ts#L632

I guess if you need to override custom keybinding events, maybe you need to [override the default behavior of the extension config](https://github.com/surmon-china/vue-codemirror#basic-setup), like this:

```js
app.use(VueCodemirror, {
  // keep the global default extensions empty
  extension: []
})
```

**Comment by nhumrich** [comment]
I tried this code block before submitting this issue. Then, I tried doing `extensions` instead and that fixed the issue. So I submitted a pr for that one character doc issue: https://github.com/surmon-china/vue-codemirror/pull/151

Otherwise, the issue/bug is just the order of extensions. So if I override them at root, then add the basicSetup back in at the end, everything works great. 

Thanks for the help.

**Comment by adwellj** [comment]
Setting the global `extensions` to an empty array removed all functionality (syntax highlighting, line numbers, etc.).

I was able to get Mod-Enter to work by setting a high precedence as shown in the [Extensions section](https://codemirror.net/docs/guide/#extension) of the guide.

We first need to import `keymap` and `Prec`.
```
import { keymap } from "@codemirror/view";
import { Prec } from "@codemirror/state";
import { javascript } from "@codemirror/lang-javascript";
```

This where you define your extensions, use `Prec.high` to create a keymap that will override the default `Mod-Enter`.
```
async mounted() {
  this.extensions = [
    Prec.high(
      keymap.of([
        { key: "Mod-Enter", preventDefault: true, run: this.modExec },
      ])
    ),
    javascript(),
  ];
}
```

Thanks @nhumrich and @surmon-china for pointing me towards the right direction!
