### ISSUE TITLE
Add example of undo and redo from buttons

### ISSUE THREAD

**Issue by rubjo** [surmon-china/vue-codemirror#154]
### Clear and concise description of the problem

I find it hard to understand the new v6 docs. How would I import / set up vue-codemirror so that I can issue eg. undo and redo commands to the editor programmatically? An example would be of great help.

### Suggested solution

?

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by surmon-china** [comment]
Codemirror@6's default basic-setup already integrates shortcut capabilities regarding history.

- https://github.com/codemirror/basic-setup/blob/main/src/codemirror.ts#L54
- https://github.com/codemirror/basic-setup/blob/main/src/codemirror.ts#L72

Document:

- https://github.com/codemirror/commands
- https://codemirror.net/docs/ref/#h_undo_history

You can use shortcuts on the example page to undo redo functions.

https://github.com/codemirror/commands/blob/main/src/history.ts#L387

```js
export const historyKeymap: readonly KeyBinding[] = [
  {key: "Mod-z", run: undo, preventDefault: true},
  {key: "Mod-y", mac: "Mod-Shift-z", run: redo, preventDefault: true},
  {linux: "Ctrl-Shift-z", run: redo, preventDefault: true},
  {key: "Mod-u", run: undoSelection, preventDefault: true},
  {key: "Alt-u", mac: "Mod-Shift-u", run: redoSelection, preventDefault: true}
]
```

If you need to customize the ability to invoke undo/redo, you can refer to the example code [here](https://codesandbox.io/s/codemirror-6-demo-pl8dc?file=/src/index.js).

**Comment by rubjo** [comment]
Thanks for taking the time to reply. I was more thinking of eg. separate undo/redo buttons independent from the editor, which when clicked, issued the appropriate commands to the editor. But so far I have problems even getting to the editor instance when using vue-codemirror, so I probably need to try to understand more of the documentation.

**Comment by surmon-china** [comment]
You can use the [`ready`](https://github.com/surmon-china/vue-codemirror#component-events) event to get everything you need.

```vue
<template>
  <codemirror @ready="handleReady" />
</template>

<script>
  import { shallowRef } from 'vue'
  import { Codemirror } from 'vue-codemirror'

  export default {
    components: {
      Codemirror
    },
    setup() {
      const cmView = shallowRef(null)
      const cmState = shallowRef(null)
      const handleReady = ({ view, state, container }) => {
        cmView.value = view
        cmState.value = state
        console.log(view, state, container)
      }

      return { handleReady }
    }
  }
</script>
```

**Comment by surmon-china** [comment]
@rubjo I have added the undo/redo button function to the [example page](https://github.surmon.me/vue-codemirror), you can find the source code [here](https://github.com/surmon-china/surmon-china.github.io/blob/source/examples/vue-codemirror/editor.vue#L101).

**Comment by rubjo** [comment]
Thank you so much @surmon-china 🙏🙂
