### ISSUE TITLE
多语言动态切换

### ISSUE THREAD

**Issue by virusdefender** [surmon-china/vue-codemirror#16]
简单看了下，本项目中只会按照初始化配置的语言引入对应的js文件。https://github.com/surmon-china/vue-codemirror/blob/master/codemirror.vue#L115

但是如果需要多种语言，然后互相切换的话，就会发现其他语言的js没有被引入，导致高亮和空格等出现问题。我尝试在组件外边require相关的js，貌似没有效果。

请问这个如何解决呢？

**Comment by surmon-china** [comment]
在组件调用处，使用v-if控制语言变动后重新初始化如何
```vue
<codemirror v-model="code" :options="editorOption" v-if="langChanged"></codemirror>
```

**Comment by virusdefender** [comment]
这样不是很科学吧

而且根据 http://stackoverflow.com/questions/39909764/webpack-async-loading-with-dynamic-require webpack会把codemirro所有的js都打包进去

所以我感觉在组件内部watch mode，然后动态的require对应的js就可以。

**Comment by virusdefender** [comment]
另外的问题就是打包出来的js太大了，感觉需要async loading一下。

**Comment by surmon-china** [comment]
你说得对，后期我抽时间把这些部分重新优化，感谢你的关注。

**Comment by virusdefender** [comment]
不好意思，更正一下，我开始提出的问题并不存在，是我的用法问题。因为该项目默认的mode和我默认的mode不一致导致的，而我也没有在合适的时候重新的`setOption`。

所有的语言js都会打包进去的问题还是存在的，不过不是bug。

十分感谢。

**Comment by Anyway521** [comment]
> 不好意思，更正一下，我开始提出的问题并不存在，是我的用法问题。因为该项目默认的mode和我默认的mode不一致导致的，而我也没有在合适的时候重新的`setOption`。
> 
> 所有的语言js都会打包进去的问题还是存在的，不过不是bug。
> 
> 十分感谢。

老哥这个问题有解决的办法吗？如何实现动态加载需要的语言类型

**Comment by Anyway521** [comment]
暂时的解决方案： 
```
onBeforeMount(()=>{ 
     if(props.mode ==='sql'){ 
         //require里面不要写变量
         require('codemirror/mode/sql/sql') }
    else if(props.mode==='markdown'){
         require('codemirror/mode/markdown/markdown')
} })
```
