### ISSUE TITLE
Multiple instances of @codemirror/state are loaded, breaking instanceof checks.

### ISSUE THREAD

**Issue by kquadri** [surmon-china/vue-codemirror#165]
### Describe the bug

While loading CodeMirror, i am getting this error  "Error: Unrecognized extension value in extension set ([object Object]). This sometimes happens because multiple instances of @codemirror/state are loaded, breaking instanceof checks".

### Reproduction

not

### System Info

```shell
"dependencies": { 
    "@codemirror/lang-css": "^0.20.0",
    "@codemirror/lang-html": "^0.20.0",
    "@codemirror/lang-javascript": "^0.20.1",
    "@codemirror/lang-json": "^0.20.0",
    "@codemirror/lang-xml": "^0.20.0", 
    "@quasar/extras": "^1.13.5", 
    "@types/lodash": "^4.14.178",
    "@vicons/ionicons4": "^0.12.0",
    "@vueform/multiselect": "^2.3.3", 
    "buffer": "^6.0.3",
    "chart.js": "^2.9.3",
    "core-js": "^3.20.3",
    "echarts": "^5.3.2",
    "elkjs": "^0.7.1",
    "highlight.js": "^11.4.0",
    "lodash": "^4.17.21",
    "luxon": "^2.2.0",
    "naive-ui": "^2.27.0",
    "papaparse": "^5.3.1",
    "quasar": "^2.7.1",
    "stream": "^0.0.2",
    "stream-browserify": "^3.0.0",
    "v-code-diff": "^0.3.10",
    "vue": "^3.2.33",
    "vue-chartkick": "1.1.0",
    "vue-class-component": "8.0.0-rc.1",
    "vue-codemirror": "^5.0.1",
    "vue-diff": "^1.2.0",
    "vue-draggable-next": "^2.1.1",
    "vue-echarts": "^6.0.2",
    "vue-json-pretty": "^2.0.6",
    "vue-jstree": "^2.1.6",
    "vue-meta": "3.0.0-alpha.9",
    "vue-property-decorator": "^9.1.2",
    "vue-router": "4",
    "vue-select": "^3.18.3", 
  },
```

### Used Package Manager

yarn

### Validations

- [X] Read the the documentation in detail.
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a GitHub Discussion or join our [Discord Chat Server](https://discord.surmon.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by surmon-china** [comment]
duplicate #148 

1. remove `yarn.lock` & `node_modules` & `@codemirror/x` in `package.json`
2. `yarn add codemirror vue-codemirror`

**Comment by kquadri** [comment]
@surmon-china

I'm still getting the same error.

**Comment by surmon-china** [comment]
Make sure your dependency version of `vue-codemirror` is v6.x

**Comment by walirt** [comment]
I also encountered this problem under pnpm, remove package is not work for me

**Comment by walirt** [comment]
> I also encountered this problem under pnpm, remove package is not work for me

I found that my extension was used in the wrong way, and there will be no problem after the modification.
`
Extensions = ref([
  json(),
  jsonParseLinter(),
  EditorView.lineWrapping
])
`
change into 
`
Extensions = ref([
  json(),
  linter(jsonParseLinter()),
  EditorView.lineWrapping
])
`

**Comment by smartwange** [comment]
install codemirror and @codemirror/state, 
import { basicSetup } from "codemirror";
const extensions = [basicSetup, javascript(), oneDark];
