### ISSUE TITLE
How can I use getCursor to obtain cursor position in vue3

### ISSUE THREAD

**Issue by zhangsai521314** [surmon-china/vue-codemirror#169]
### Describe the bug

How can I use getCursor to obtain cursor position in vue3

### Reproduction

How can I use getCursor to obtain cursor position in vue3

### System Info

```shell
"vue-codemirror": "^6.1.1",
    "vue": "^3.2.21",
"codemirror": "^6.0.1",
```

### Used Package Manager

yarn

### Validations

- [X] Read the the documentation in detail.
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a GitHub Discussion or join our [Discord Chat Server](https://discord.surmon.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zhangsai521314** [comment]
I See https://github.com/surmon-china/vue-codemirror

**Comment by wingjie** [comment]
How to insert the cursor into the specified position
