### ISSUE TITLE
How to set codemirror options?

### ISSUE THREAD

**Issue by shuitai** [surmon-china/vue-codemirror#174]
### Describe the bug

How to set codemirror options?
in v4 version, vue-codemirror has the api to set option, but now it cannot, if it has, please add it to example or doc.

### Reproduction

None

### System Info

```shell
None
```

### Used Package Manager

npm

### Validations

- [X] Read the the documentation in detail.
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a GitHub Discussion or join our [Discord Chat Server](https://discord.surmon.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by surmon-china** [comment]
In Codemirror@6, everything comes from [extension](https://codemirror.net/docs/guide/#extension), which replaces the original `options`, and you need to learn how to use extension.
