### ISSUE TITLE
Uncaught TypeError: Cannot set property 'content' of null

### ISSUE THREAD

**Issue by zchrissirhcz** [surmon-china/vue-codemirror#2]
使用你的repo中`example`目录所提供的代码，chrome控制台看到报错:
![image](https://cloud.githubusercontent.com/assets/3831847/18806902/ae15f182-826c-11e6-8bf3-29dd9779f9bc.png)

```
es5.js?3983:44 Uncaught TypeError: Cannot set property 'content' of null
```

这种情况下，尝试获取代码区域的内容，则获取为空。

**Comment by zchrissirhcz** [comment]
看起来是代码没有通过"use strict"的检查导致的

**Comment by surmon-china** [comment]
我测试下

**Comment by Rainboylvx** [comment]
我也出现这个错误

**Comment by surmon-china** [comment]
是函数this指向造成的问题，已修复，现在更新
