### ISSUE TITLE
vue-codemirror v3.0.0 broke support for webpack import

### ISSUE THREAD

**Issue by amoshydra** [surmon-china/vue-codemirror#22]
This change https://github.com/surmon-china/vue-codemirror/pull/21 broke support for wepback with ES6 `import`

`import VueCodeMirror from 'vue-codemirror';`
throws error:
```
Cannot assign to read only property 'exports' of object '#<Object>'
```

It seems to be related to this issue: https://github.com/webpack/webpack/issues/4039 as I am using `webpack` and ES6 `import` in my project.

vue-codemirror 2.1.8 does not have this problem

**Comment by surmon-china** [comment]
v3.0.3 fix it.

**Comment by amoshydra** [comment]
Upgraded to v3.0.3.
It is now working now. Thanks!
