### ISSUE TITLE
The editor cannot wrap lines automatically, and horizontal scrolling has a scroll bar

### ISSUE THREAD

**Issue by snowbitx** [surmon-china/vue-codemirror#228]
### Describe the bug

After installation according to the steps of the official website, the editor can't wrap automatically, and when Baidu adds the configuration item lineWrapping to true, it doesn't take effect either
![image](https://github.com/user-attachments/assets/972419f3-a4d5-4770-ae20-717c5221bafe)
![image](https://github.com/user-attachments/assets/fa752c85-a83d-4b95-a8f7-61c37fcc2d2a)

### Reproduction

After installation according to the steps of the official website, the editor can't wrap automatically, and when Baidu adds the configuration item lineWrapping to true, it doesn't take effect either

### System Info

```shell
After installation according to the steps of the official website, the editor can't wrap automatically, and when Baidu adds the configuration item lineWrapping to true, it doesn't take effect either
```

### Used Package Manager

npm

### Validations

- [X] Read the the documentation in detail.
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a GitHub Discussion or join our [Discord Chat Server](https://discord.surmon.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by XiaoMouz** [comment]
auto wrap: https://github.com/surmon-china/vue-codemirror/issues/214#issuecomment-1870425830

**Comment by snowbitx** [comment]
Thank you very much for your reply. The issue has been resolved.
