### ISSUE TITLE
can not use mime outside `CodeMirror.modeInfo`

### ISSUE THREAD

**Issue by leo108** [surmon-china/vue-codemirror#24]
For example, the [php mode](https://github.com/codemirror/CodeMirror/blob/master/mode/php/php.js) defines mime type `application/x-httpd-php-open` and `text/x-php` but not listed in [modeInfo](https://github.com/codemirror/CodeMirror/blob/master/mode/meta.js), if I set `mode: 'application/x-httpd-php-open'` it says `CodeMirror language mode: undefined configuration error` in console.

I have tried to set `mode: { name: 'php', startOpen: true}`, but it was replaced with `mode: 'php'` before passing to CodeMirror's `fromTextArea` method at https://github.com/surmon-china/vue-codemirror/blob/master/codemirror.vue#L55

**Comment by surmon-china** [comment]
Thanks for the feedback, I'll take a closer look at the problem.

**Comment by surmon-china** [comment]
https://github.com/codemirror/CodeMirror/pull/130

Yes, I think what you describe is the normal expected performance.
At present, because you want to use the language type in the non metas.js list, you must manually import the php.js file before defining the `application / x-httpd-php-open` mode, and the cobalt theme package does not support` application / X-httpd-php-open` / `text / x-php`, the reason is unknown, you can use other themes highlight,
If you have a better attempt or a solution, welcome to submit the PR contribution

```javascript
require('codemirror/mode/php/php.js')
return {
        code: '$phpcode = ""',
        editorOption: {
          tabSize: 4,
          styleActiveLine: true,
          lineNumbers: true,
          line: true,

          // mode: 'text/x-php',  /* it works, but can't use the cobalt theme */
          // mode: 'application/x-httpd-php', /* it works */
          mode: 'application/x-httpd-php-open', /* it works, manually require php.js and can't use the cobalt theme */
          // mode: { name: 'php', startOpen: true }, /* it works */
          lineWrapping: true,
          // theme: 'cobalt', /* it can't works with `application/x-httpd-php-open` and `text/x-php` */
          theme: 'ambiance'
        }
      }

```

**Comment by leo108** [comment]
I have tried to require `codemirror/mode/php/php.js` at the start of js script but still told me `CodeMirror language mode: undefined configuration error`.

Here is my test .vue file

```
<template>
  <codemirror v-model="code" :options="options"></codemirror>
</template>

<script>
require('codemirror/mode/php/php.js');

export default {
  name: 'app',
  components: {codemirror: require('vue-codemirror').codemirror},
  data() {
    return {
      code: '',
      options: {
        mode: 'application/x-httpd-php-open', // it works if set to  application/x-httpd-php
        tabSize: 4,
        styleActiveLine: true,
        lineNumbers: true,
        line: true,
        lineWrapping: true,
        theme: 'monokai'
      }
    }
  }
}
</script>
```

BTW, I'm using vue-codemirror@3.0.4

**Comment by surmon-china** [comment]
Does it work actually?

**Comment by leo108** [comment]
@surmon-china of course not

**Comment by leo108** [comment]
Indeed, I'm curious why you said it's the normal behavior, it drops options we try to passing to the real CodeMirror.

What ever the mode options we passing to codemirror component, it will always be replaced with a **string** due to the code below:

```
language = lang.mode
this.options.mode = language
```

will result in

**Comment by surmon-china** [comment]
Because the component is to ensure that only the packages of the language patterns you set are introduced, if you do not do so, your language pack will take up a large portion after your application is packaged.
I am in the process of local testing, in addition to a warning message, he is able to work properly, I am ready to use a new vue program, test this problem.

**Comment by leo108** [comment]
`language = lang.mode` is necessary for loading the language package, but what's the purpose of `this.options.mode = language`?

**Comment by surmon-china** [comment]
You are right, i am updating this.

**Comment by leo108** [comment]
It works after upgraded to 3.0.5

**Comment by surmon-china** [comment]
Update to v3.0.5, it should be work!😆

```vue
<codemirror v-model="code" :options="editorOption" :debugger="false"></codemirror>

<script>
  require('codemirror/mode/php/php.js')
  export default {
    components: {
      codemirror: require('components/vue-codemirror').codemirror
    },
    data() {
      return {
        code: `<?php  echo "$a[a] \${a[3] /* } comment */} {$a[b]} $a[a]"; ?>`,
        editorOption: {
          tabSize: 4,
          styleActiveLine: true,
          lineNumbers: true,
          line: true,
          // mode: 'text/x-php',
          // mode: 'application/x-httpd-php',
          mode: 'application/x-httpd-php-open',
          // mode: { name: 'php', startOpen: true },
          lineWrapping: true,
          theme: 'cobalt'
        }
      }
    }
  }
</script>
```

**Comment by surmon-china** [comment]
Previously the subject style can not use the problem, because the components of the conditions of the branch is not standardized caused by this is really a stupid mistake, thank you for your feedback, good luck!
