### ISSUE TITLE
vue-codemirror已经不支持vue1了吗

### ISSUE THREAD

**Issue by chanyying** [surmon-china/vue-codemirror#25]

**Comment by surmon-china** [comment]
不支持啦，需要支持1.0的话降级到v3.0.0以前的版本呦

**Comment by chanyying** [comment]
@surmon-china 3.0以前的版本，也不起作用了。其他人install的时候更新代码了，但是版本在3.0以前的

**Comment by surmon-china** [comment]
要重装一遍呦
`npm i vue-codemirror@2.1.6 --save`
