### ISSUE TITLE
How to load CSS ?

### ISSUE THREAD

**Issue by rafalolszewskii** [surmon-china/vue-codemirror#27]
Hi, I've succesfully loaded CodeMirror via your package, although I can't get css to work, is there any extra step required to get the correct CSS to make CodeMirror look like it supposed to ?

**Comment by surmon-china** [comment]
```javascript
editorOptions: {
        theme: 'base16-dark'
}
```

Doesn't it work?

**Comment by surmon-china** [comment]
http://codemirror.net/demo/theme.html
