### ISSUE TITLE
Unknown custom element issue

### ISSUE THREAD

**Issue by BMLande** [surmon-china/vue-codemirror#31]
I having Following can u please provide solutions?

[Vue warn]: Unknown custom element: <md-card> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Codedemo> at /home/bhagvat/work/HowToUSe/codedemo/src/components/codedemo.vue
       <App> at /home/bhagvat/work/HowToUSe/codedemo/src/App.vue
         <Root>

**Comment by surmon-china** [comment]
Obviously, depending on the error message that should be caused by your actual code, you should provide the code for the two component files you described above.

**Comment by BMLande** [comment]
thank u sir i splve tghis isssue ...thanks for ur reply

**Comment by arsh13** [comment]
Hey @BMLande , how did you fix this issue? I'm facing the same problem after following https://github.com/surmon-china/surmon-china.github.io/tree/source/projects/vue-codemirror/nuxt
