### ISSUE TITLE
Feature request - ability to use external theme

### ISSUE THREAD

**Issue by Madd0g** [surmon-china/vue-codemirror#35]
I found this repo - https://github.com/FarhadG/code-mirror-themes

But there's no way of using these external themes because of [this line](https://github.com/surmon-china/vue-codemirror/blob/master/codemirror.vue#L49):

      // require theme
      if (theme) {
        require('codemirror/theme/' + theme + '.css')
      }

Can we somehow make this optional?

Thanks

**Comment by surmon-china** [comment]
@Madd0g Thanks for feedback! This is a very valuable question, do you have any good solution, you can submit your suggestions!

**Comment by Madd0g** [comment]
I'm using webpack, when I'm including the stylesheet myself, there's no need for the automatic require. For me, something like `loadTheme: false` would solve the problem.

    import 'code-mirror-themes/themes/github.css'
    let editorOptions = {
        ...
        theme: 'github',
        loadTheme: false,
        ...
    }

**Comment by surmon-china** [comment]
@Madd0g 

![image](https://user-images.githubusercontent.com/14019524/28447396-11c72bba-6e03-11e7-8329-50bc8d200fde.png)

This problem is solved, the biggest problem is that you need to manually configure the `toolbar` option, he corresponding to each option` value` value will be inserted as inline data, good luck!

like this:

![image](https://user-images.githubusercontent.com/14019524/28447441-546eafba-6e03-11e7-9f89-7779891277f2.png)

In vue:

```html
<quill-editor ref="myTextEditor"
              v-model="content"
              :options="editorOption"
              @blur="onEditorBlur($event)"
              @focus="onEditorFocus($event)"
              @ready="onEditorReady($event)">
  <div id="toolbar" slot="toolbar">
    <span class="ql-formats">
      <select class="ql-size">
        <option value="10px">Small</option>
        <option selected>Normal</option>
        <option value="18px">Large</option>
        <option value="32px">Huge</option>
      </select>
    </span>
    <span class="ql-formats">
      <select class="ql-color">
        <option selected></option>
        <option value="red"></option>
        <option value="orange"></option>
        <option value="yellow"></option>
        <option value="green"></option>
        <option value="blue"></option>
        <option value="purple"></option>
      </select>
      <select class="ql-background">
        <option selected></option>
        <option value="red"></option>
        <option value="orange"></option>
        <option value="yellow"></option>
        <option value="green"></option>
        <option value="blue"></option>
        <option value="purple"></option>
      </select>
    </span>
  </div>
</quill-editor>
```

```javascript
editorOption: {
  modules: {
    toolbar: '#toolbar'
  },
  placeholder: 'Compose an epic...'
}
```

**Comment by surmon-china** [comment]
@Madd0g 

Update to v3.1.2 please, it will be work!

Since I hope that the `options` attribute is passed in a pure, and `codemirror` consistent with the api option, the `loadtheme` attribute is configured on the component.

use:

```html
<codemirror v-model="code" :options="editorOption" :loadtheme="false"></codemirror>
```

```javascript
require('code-mirror-themes/themes/birds-of-paradise.css')

editorOption: {
  ...
  theme: 'birds-of-paradise',
  ...
}
```
