### ISSUE TITLE
Set mode 'text/x-vue', but require all mode when build, how to fix this?

### ISSUE THREAD

**Issue by jovey-zheng** [surmon-china/vue-codemirror#36]
Anyone have this problem? I just use `vue` mode, but get all mode when build the project.

```js
editorOption: {
          tabSize: 4,
          styleActiveLine: true,
          line: true,
          mode: 'text/x-vue',
          lineWrapping: true,
          theme: 'monokai',
          matchBrackets: true,
          foldGutter: true,
          gutters: ['CodeMirror-linenumbers', 'CodeMirror-foldgutter'],
}
```

build result:
![image](https://user-images.githubusercontent.com/9565245/28658295-25367370-72dd-11e7-82a8-0db4cb678cc8.png)

**Comment by surmon-china** [comment]
This question is very important, I will take the time to solve the depth, thank you for your feedback!

**Comment by surmon-china** [comment]
I'm sorry, this problem may not have a better solution at this time, because the webpack require api decides that the compiler can not parse the runtime context, and if you have a better solution, welcome you to submit pr!

**Comment by papersnake** [comment]
一样的问题，打包出来的JS打大了，

**Comment by surmon-china** [comment]
4.0 将彻底修复这个问题。
