### ISSUE TITLE
not found "remove" property when beforeDestory in IE10

### ISSUE THREAD

**Issue by snuser** [surmon-china/vue-codemirror#37]
###
 beforeDestroy: function beforeDestroy() {
     this.editor.doc.cm.getWrapperElement().remove();
   },
###
not found remove property
![t1d7zvbjyg1rcvbvdk](https://user-images.githubusercontent.com/2217708/29125025-2e49561a-7d4d-11e7-9c03-c8f1b50fd22b.png)

**Comment by surmon-china** [comment]
The v3.1.4 fix it, it will be work!
