### ISSUE TITLE
it is not compatible with vue ssr project.

### ISSUE THREAD

**Issue by brandonxiang** [surmon-china/vue-codemirror#43]
```
  require('codemirror/lib/codemirror.css')
```
That will affect that the webpack cannot build project.

**Comment by dinho-afsn** [comment]
Yes is compatible
needs only a few adjustments

remove the plugin from the node_modules folder, and use:
in (/vue-codemirror/index.js)

if(process.browser) {

put all the contents of index.js here

} 

now works perfectly!

**Comment by surmon-china** [comment]
https://github.com/surmon-china/vue-codemirror#mount-with-ssr
https://github.com/surmon-china/vue-codemirror#component
