### ISSUE TITLE
element UI 兼容问题

### ISSUE THREAD

**Issue by EverCurse** [surmon-china/vue-codemirror#45]
在elementui中使用dialog显示code mirror，
总要点击面板code mirror才能显示最新的文本
于是想到了auto fucus，但是时而生效 时而不生效
不知道这是不是兼容性问题

`
      <el-dialog :visible.sync="view_sql_ctrl" :modal="false" size="large">
        <div class="codemirror">
        <codemirror :options="createScriptOptions" v-model="sql_detail"></codemirror>
        </div>
      </el-dialog>`

**Comment by surmon-china** [comment]
尝试这样：

```javascript
<!-- 查看脚本dialog -->
<el-dialog :visible.sync="view_sql_ctrl" :modal="false" size="large">
  <div class="codemirror">
    <codemirror v-if="view_sql_ctrl" :options="createScriptOptions" v-model="sql_detail"></codemirror>
  </div>
</el-dialog>
```

**Comment by EverCurse** [comment]
@surmon-china  thx 已解决

**Comment by sunsmeil** [comment]
同问

**Comment by songlin51** [comment]
加个 v-if 判断下就可以了
