### ISSUE TITLE
How to use addon/merge

### ISSUE THREAD

**Issue by FroilanYue** [surmon-china/vue-codemirror#46]
Hi,

For some reason, I need to use `addon/merge/merge.js` of codemirror.

There are difference of constructor between normal codemirror and mergeview:
merge.js suggests to use
```javascript
this.editor = CodeMirror.MergeView()
```
However I notice this tool construct a codemirror by
```javascript
this.editor = CodeMirror.fromTextArea()
```

So, despite it supports to require some addons, there might be no way to construct a mergeview?

Thanks

**Comment by surmon-china** [comment]
@FroilanYue This should require updating the component, please wait for the next version, not too long!

**Comment by surmon-china** [comment]
update to v4.0.0 please.

**Comment by cleemansen** [comment]
Is the merge-view also available in your codemirror-6 based version?
