### ISSUE TITLE
error when using nuxt/ssr

### ISSUE THREAD

**Issue by zhang156** [surmon-china/vue-codemirror#47]
when i use with nuxt making ssr false,
```
{src: '~/plugins/codemirror', ssr: false}
```
codemirror.js
```
import Vue from 'vue'
import VueCodeMirror from 'vue-codemirror'

Vue.use(VueCodeMirror)
```
the page use the component
```
<el-form-item label="文章内容">
    <codemirror v-model="form.code" :options="editorOptions"></codemirror>
</el-form-item>
```

it works well when routing from different page, but it failed when reload the page
```
The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside, or missing . Bailing hydration and performing full client-side render.
```
How to solve this issue? Thanks in advance :)

**Comment by surmon-china** [comment]
#43

**Comment by dinho-afsn** [comment]
try
let VueCodeMirror
if(process.browser) {
VueCodeMirror = require('vue-codemirror')
}

or
remove the plugin from the node_modules folder, and use:
in (/vue-codemirror/index.js)

if(process.browser) {

put all the contents of index.js here

}

**Comment by Valar103769** [comment]
> try
> let VueCodeMirror
> if(process.browser) {
> VueCodeMirror = require('vue-codemirror')
> }
> 
> or
> remove the plugin from the node_modules folder, and use:
> in (/vue-codemirror/index.js)
> 
> if(process.browser) {
> 
> put all the contents of index.js here
> 
> }
> 
> the problem is that nuxt tries to run window on the server side and is wrong, tell nuxt that it will only be rendered on the client side

it's VueCodemirror,not VueCodemirror, and this skill is invalidable
