### ISSUE TITLE
webpack package all the modes and themes because of the wrong "require"

### ISSUE THREAD

**Issue by lijing666** [surmon-china/vue-codemirror#50]
### 中文描述

webpack构建时，对于这种动态计算的路径require('codemirror/mode/' + language + '/' + language + '.js')，会将codemirror/mode下的所有文件都打包到项目中，所以这边的代码按需引入是无效的，只能用户在外边自己引入所需mode和theme	
  		  
### English Description

when use webpack build，because of the use of  [ require('codemirror/mode/' + language + '/' + language + '.js')]，webpack packages all the modes  and the themes into the dist but not the specified language mode。

**Comment by lijing666** [comment]
solved it，add webpack plugin like this can only add the special modes and themes：
new webpack.ContextReplacementPlugin(
      /codemirror[\/\\]mode$/,
      /javascript/
    ),
    new webpack.ContextReplacementPlugin(
      /codemirror[\/\\]theme$/,
      /eclipse/
    ),

**Comment by surmon-china** [comment]
对，所以 v4.0.0 将只保留核心库，其他任何资源（包括语言包 + 样式）本身，都需开发者手动引入。
