### ISSUE TITLE
shell脚本怎么配置

### ISSUE THREAD

**Issue by pfpGit** [surmon-china/vue-codemirror#52]
如题，语法高亮设置可以，但是怎么让插件可以想shell那样自动完成

`editorOption: {
        tabSize: 4,
        styleActiveLine: true,
        line: true,
        mode: 'text/x-sh',
        lineWrapping: true,
        theme: 'base16-dark',
        scrollbarStyle: null,
      }`

**Comment by surmon-china** [comment]
像 shell 一样是做不到的，可以像 codemirror 一样。
https://github.com/surmon-china/vue-codemirror/blob/master/examples/02-text-javascript.vue
