### ISSUE TITLE
Get event change on $emit

### ISSUE THREAD

**Issue by dinho-afsn** [surmon-china/vue-codemirror#53]
Hello my friend,
How to get code after inserted?

I tried to capture the change event but without success
I'm trying
this.$on
this.$root.$on (....
but without success, could you inform me a way to get the code after inserting it into the editor?

**Comment by surmon-china** [comment]
https://github.com/surmon-china/vue-codemirror#component
`@input="codeChange()"`
`codemirror.$on('input', code => {})`

**Comment by dinho-afsn** [comment]
Thank you!
