### ISSUE TITLE
Lazy loading modes

### ISSUE THREAD

**Issue by wardy484** [surmon-china/vue-codemirror#54]
Is it possible to lazy load modes like? 

I'm starting to think that it is not because the modes are loaded in through require. If it is could you provide an example.

**Comment by ddonng** [comment]
warning  in ./node_modules/_codemirror@5.41.0@codemirror/addon/mode/loadmode.js

Critical dependency: the request of a dependency is an expression

**Comment by surmon-china** [comment]
@wardy484 

Try this code:

```js
import codemirror form 'codemirror'
const CodeMirror = codemirror.CodeMirror
CodeMirror.modeURL = 'your_cdn_language_mode_path'
CodeMirror.autoLoadMode(yourCmInstance, <mode>)
```

**Comment by 625781186** [comment]
@surmon-china 
可以提供一个例子吗. 

![image](https://user-images.githubusercontent.com/30521429/76044090-407db480-5f94-11ea-914a-52a8a092b278.png)

![image](https://user-images.githubusercontent.com/30521429/76044019-0d3b2580-5f94-11ea-8055-65e417be3ac4.png)

用绝对路径测试也找不到这个模块.

**Comment by jonalxh** [comment]
Not working for me. Is there a new implementation?
