### ISSUE TITLE
How to upgrade vue-codemirror from v3 to v4?

### ISSUE THREAD

**Issue by layanto** [surmon-china/vue-codemirror#55]
How to upgrade vue-codemirror from v3 to v4?

I have tried updating my package.json to refer to ^4.0.0 and change .editor reference to .codemirror, but not displaying codemirror editor at all. Reverting back to ^3.0.0 works.

Any guidance on how to upgrade from v3 to v4?

**Comment by surmon-china** [comment]
You may need to see the latest instructions for [CHANGELOG.md](https://github.com/surmon-china/vue-codemirror/blob/master/CHANGELOG.md), and README.md because there are some incompatible updates.

**Comment by layanto** [comment]
I still can't get v4 to work. 

This is how I configure v3. Working fine but when changing package.json to v4 and updating npm, I get empty screen - no CodeMirror and also no error in console.

```javascript
<template>
<codemirror v-model="data" :options="editorOptions" />
</template>
<script>
import { codemirror } from 'vue-codemirror'
import 'codemirror/addon/selection/active-line.js'
export default {
    components: {
        codemirror
    },
    data () {
        return {
            data: '',
            editorOptions: {
                readOnly: false,
                indentUnit: 4,
                mode: 'text/javascript',
                theme: 'base16-dark',
                styleActiveLine: true,
                extraKeys: {
                    Tab: function (cm) {
                        if (cm.somethingSelected()) {
                            cm.indentSelection('add')
                        } else {
                            cm.execCommand('insertSoftTab')
                        }
                    },
                    'Shift-Tab': function (cm) {
                        cm.indentSelection('subtract');
                    }
                }
            }
        }
    }
</script>
<style>
    .CodeMirror {
        height: 800px;
    }
</style>
```

**Comment by surmon-china** [comment]
You need import the codemirror css.

```javascript
import 'codemirror/lib/codemirror.css'
```

**Comment by layanto** [comment]
I didn't need to do that with v3.
I have added import CSS on v4, now I see codemirror instance but it has default style. It appears that the theme I set in the option is not applied.

**Comment by layanto** [comment]
Looks like I need to import CSS specific to the theme set. This must somehow be done automatically with v3.

import 'codemirror/theme/base16-dark.css'

**Comment by layanto** [comment]
With import 'codemirror/lib/codemirror.css', vue-codemirror v4 is working. But with import 'codemirror/theme/base16-dark.css', codemirror is not working. I cannot set focus to codemirror and cannot enter text into the editor. All I see is black background.

**Comment by layanto** [comment]
Seems like the actual editor is offset to outside of the black background area - hence I thought the editor is missing. Not sure why the offset is all wrong with any theme, without theme working fine.

**Comment by layanto** [comment]
Probably issue with webpack hot reload. Seems to work correctly now with base16-dark theme

**Comment by wuliupo** [comment]
thanks @layanto, I find readOnly parameter here :)
