### ISSUE TITLE
modes are not 'mounted'

### ISSUE THREAD

**Issue by achtan** [surmon-china/vue-codemirror#56]
hi, i have this code:
`````js
import VueCodemirror from 'vue-codemirror'
import CodeMirror from 'codemirror';
import 'codemirror/lib/codemirror.css'
import 'codemirror/mode/javascript/javascript.js'
console.log(VueCodemirror.CodeMirror.modes);
console.log(CodeMirror.modes);
`````
and this is the log result:
`````js
Object {null: function}
Object {null: function, javascript: function}
`````

any idea how to load mode into the vue-codemirror instance?

**Comment by surmon-china** [comment]
I'm sorry, I did not get this exception, you are using the latest version?

![image](https://user-images.githubusercontent.com/14019524/35051950-5c57a76a-fbe1-11e7-8549-eb0d8dc889ae.png)

Maybe you can use this:

```javascript
import VueCodemirror, { CodeMirror } from 'vue-codemirror'
```

**Comment by HOTTIN** [comment]
最新的版本v4.0.6好像也有这个问题，按照demo写出来的代码不会高亮
