### ISSUE TITLE
vue1.0版本中使用codemirror，它的@changed方法不被触发

### ISSUE THREAD

**Issue by haoxutong** [surmon-china/vue-codemirror#6]
<codemirror :code="code" :options="editorOption" @changed="codeChange"></codemirror>
methods:{
		
			codeChange(newCode){
				console.log('newCode',newCode);
				this._changeSQL(this.uid,newCode)
			},
}
遇到两个问题，一个是codeChange方法不被触发，当我修改代码的时候，还有就是引入	<script src="hint/show-hint.js"></script>
	<script src="hint/sql-hint.js"></script>这两个文件的配置项没有起作用，
我是直接在data中加配置项的
data(){
			return {
				//codemirror的配置项
				editorOption:{
				    lineNumbers: true,//设置行号 boolean
				    mode: 'text/x-mysql',//当前code模式 模式的选择可以在CodeMirror.modes中查看
				    //此处是引用sql-hint.js的配置项
				    hintOptions:{
				    	completeSingle: false, //当匹配只有一项的时候是否自动补全
		                   tables: {
		                       table1: ['name', 'score', 'birthDate'],
		                       table2: ['name', 'population', 'size']
		                   }
				    },//表元信息
				    extraKeys: {//快捷键 可提供三种模式 sublime、emacs、vim。 使用时需要引入js支持包
				        "F9": function (editor) {
				            format(editor);
				        },
				        "F8": function (editor) {
				            query(editor);
				        }
				      }
				}
			}
		}

**Comment by surmon-china** [comment]
@changed方法是给2.0用的

1.0你可以通过下面这些方式应用

```vue
<!-- 单向数据绑定（即codemirror的变化不会再响应回来） -->
<codemirror :code="code" :options="editorOption"></codemirror>
<!-- 双向数据绑定（2.0已废弃） -->
<codemirror :code.sync="code" :options="editorOption"></codemirror>
```

如果你要监听codemirror 的变化，可以双向数据绑定，并且在watch中watch你所绑定的变量，然后作出相应操作

**Comment by haoxutong** [comment]
哦  那请问你这插件可以加入	<script src="hint/show-hint.js"></script>
	<script src="hint/sql-hint.js"></script>这个两个js文件的配置项 实现autocomplete吗  我试着在editOption中加了  没有起作用

**Comment by surmon-china** [comment]
如果有 hint/show-hint.js 来源的详细信息，可以提供一下

**Comment by surmon-china** [comment]
找到了，下一个版本增加/修复此功能，本周内完成

**Comment by haoxutong** [comment]
哇塞  果然是大神  坐等下一个版本  给你点32个赞

**Comment by haoxutong** [comment]
还有一个比较大的问题 现在code数据不是放在data中 是放在computed中计算属性得到的，这样我改变其值，如何检测其变化，将计算属性的来源值改变
computed:{code() getTabData.sql}
我要在改变codemirror中的值时候去改变 getTabData.sql的值，应该如何去做？

**Comment by surmon-china** [comment]
文档通读一遍，这个问题就解决了

**Comment by haoxutong** [comment]
你是指vue的文档还是你的组件文档 找了一遍没找着 球指教

**Comment by surmon-china** [comment]
https://github.com/surmon-china/vue-codemirror#use-in-components

已支持
