### ISSUE TITLE
click the line-number gutter to add or remove 'breakpoints' in vue-codemirror

### ISSUE THREAD

**Issue by IvyLian** [surmon-china/vue-codemirror#67]
如何用vue-codemirror 添加breakpoints 效果，是gutterClick 这个事件么？怎么调用呢？

**Comment by IvyLian** [comment]
以下是我的代码：
return {
			isShow:true,

			// codemirror 
			code,
      cmOption: {
        autoCloseBrackets: true,
        tabSize: 4,
        styleActiveLine: true,
        lineNumbers: true,
        line: true,
        mode: 'text/x-python',
        theme: 'paraiso-light',
        keyMap: "sublime",
        lineWrapping: true,
        foldGutter: true,
        gutters: ["CodeMirror-linenumbers", "breakpoints"]
      }
		};
     components: {
	    codemirror
	},
	methods:{
		onCmReady(cm) {
	      console.log('the editor is readied!', cm)
        this.$refs.codemirror.gutterClick();  
	    },
	    onCmFocus(cm) {
	      console.log('the editor is focus!', cm)
	    },
	    onCmCodeChange(newCode) {
	      console.log('this is new code', newCode)
	      this.code = newCode
	    },
	},
回报错：Cannot read property 'gutterClick' of undefined
Error in event handler for "ready": "TypeError: Cannot read property 'gutterClick' of undefined"

**Comment by IvyLian** [comment]
很开心的说，今天晚上终于解决了这个问题，现在写上方法：
在这里加上@gutterClick='gutterClick' 这个事件
<codemirror ref="myCm"
              :value="getCode"
              :options="cmOption"
              @ready="onCmReady"
              @focus="onCmFocus"
              @input="onCmCodeChange"
              @gutterClick='demo'
              > // 加上这个事件
</codemirror>

之后在methods中定义：
 gutterClick(cm,n){
        var info = cm.lineInfo(n);
        cm.setGutterMarker(n, "breakpoints", info.gutterMarkers ? null : this.makeMarker());
}
这样，断点功能就加上了

**Comment by surmon-china** [comment]
```html
<codemirror ref="myCm"
            :value="getCode"
            :options="cmOption"
            @ready="onCmReady"
            @Focus="onCmFocus"
            @input="onCmCodeChange"
            @gutterClick='gutterClick' />
```

```javascript
makeMarker() {
  const marker = document.createElement("div")
  marker.style.color = "#FA7A6D"
  marker.innerHTML = "●"
  return marker
},
gutterClick(cm, n) {
  const info = cm.lineInfo(n)
  cm.setGutterMarker(n, "breakpoints", info.gutterMarkers ? null : this.makeMarker())
}
```

**Comment by ToJen** [comment]
@surmon-china will this be implemented in a new version

**Comment by surmon-china** [comment]
@ToJen Yes. Thx!

**Comment by lin19950219** [comment]
@surmon-china 使用CodeMirror-foldgutter时有折叠标记的地方无法有断点标记呢？
