### ISSUE TITLE
cursorActivity 无法使用

### ISSUE THREAD

**Issue by kingrome2017** [surmon-china/vue-codemirror#76]
`<codemirror 
                                    v-model="msg" 
                                    class="textarea"
                                    @scroll="onCmScroll"
                                    @focus='focus'
                                    @cursorActivity='onCmCursorActivity'
                                    :options="cmOption">
                                  </codemirror>`

` Vue.use(VueCodemirror,{events: ['cursorActivity']})`   不好使

`Vue.use(VueCodemirror,{events: ['scroll']})` 好使，成功的打印出了scrollTop值

另外你的代码 如何在本地跑起来

**Comment by surmon-china** [comment]
用 `this.codemirror.on(evennt, hanger)` 这种方式测试下

**Comment by surmon-china** [comment]
Merge #77
