### ISSUE TITLE
editor instance accessibility

### ISSUE THREAD

**Issue by gyamxxx** [surmon-china/vue-codemirror#8]
Hi, I'm sorry poor English.

 I'm using this library. Thank you for making.
so, I want to use "Autoformart" function like this.
https://codemirror.net/2/demo/formatting.html

but, editor instance cannot access parant component.
https://github.com/surmon-china/vue-codemirror/blob/master/codemirror.vue#L69

Could you make editor instance accessible, or add function like calling parent method?

**Comment by yahtnif** [comment]
@gyamxxx 

assign a reference ID to the component using `ref`
```
<codemirror v-model="code" ref="codemirror"></codemirror>
```

then access the editor instance
```
this.$refs.codemirror.editor
```

**Comment by gyamxxx** [comment]
I did it!
Thank you very much.

**Comment by jingyuLin1999** [comment]
How to get editor? I wan to get editor like this.
```js
var editor = CodeMirror.fromTextArea(document.getElementById("code"), {
        lineNumbers: true,
        mode: "htmlmixed",
        extraKeys:{"Shift-Tab":autoFormatSelection}
      });
```
howerer I get 'undefined' by this.$refs.codemirror.editor.
