### ISSUE TITLE
how i can set name current textarea field in component ?

### ISSUE THREAD

**Issue by j9k3r** [surmon-china/vue-codemirror#82]
Hello, i use basic template and i don't understand how i can set name for textarea field...
what should I do for this ?

P.S. Sorry for the trouble

**Comment by j9k3r** [comment]
i can use...
mounted() {`
this.$refs.myCm.codemirror.getTextArea().setAttribute('name','test');
}`

**Comment by surmon-china** [comment]
I will add this feature at next version, thanks for your feedback! @j9k3r

**Comment by surmon-china** [comment]
@j9k3r update to v4.0.6, add prop `name`
