### ISSUE TITLE
修改光标的位置

### ISSUE THREAD

**Issue by wty8023** [surmon-china/vue-codemirror#87]
![image](https://user-images.githubusercontent.com/27050415/52633212-a79a7800-2efe-11e9-8471-3bd32d3ae6ab.png)
我想让光标靠左 但是left值无法修改 需要如何操作

**Comment by airid** [comment]
我也遇到相同问题了,求解决方法

**Comment by wty8023** [comment]
我发现是父元素有一些样式影响的

**Comment by airid** [comment]
add CSS
```
.CodeMirror-line {
  text-align: left;
}
```
