### ISSUE TITLE
vue@2.1.4需要点击一下才会显示代码

### ISSUE THREAD

**Issue by vincent19376** [surmon-china/vue-codemirror#9]
vue@2.1.4，需要点击一下代码区，才会显示代码

**Comment by KeyaJohn** [comment]
vue@2.1.4，需要点击一下代码区，才会显示代码

**Comment by KeyaJohn** [comment]
vue@2.1.4，需要点击一下代码区，才会显示代码   有什么方式解决么？

**Comment by KeyaJohn** [comment]
Need to click on the code area to display the code. Is there any way to solve it?

**Comment by surmon-china** [comment]
#45 @KeyaJohn @hryyan 提问题，上下文描述清楚，按照模板来
